Estudo do padrao repository, service e controller
HelenaPetruz/Confeitaria pull request #3
Opened 2024-08-09 22:27 UTC by HelenaPetruz

2024-08-11 18:26 UTC, alcantaraleo requested changes
Muito bom código!

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/classes/Cliente.java
> +        this.idCliente = id;
Marcando aqui para lembrar que temos um problema com a geração de ID. 

Eu acho que já entendi o porque. 

Tente dar uma quebrada de cabeçada para ver se você acha. Mas caso queira fazer um teste, depois numa branch separada faz o repositório gerar o ID ao inves de na construtora e veja se resolve.

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/controler/ClienteController.java
> +            public ClienteController(ClienteService clienteService){
Para todas as classes que a gente for construir a partir de agora, vamos usar essa maneira de "injetar" as dependencias delas. 

Ou seja, apesar de existir o `@Autowired` e ser bom você saber sobre essa anotação, quando temos um construtor que tem os objetos que essa classe depende, o Spring automagicamente descobre as dependências e injeta para você. 

Em outras palavras, nessa construtora que tem como parâmetro a `ClienteService clienteService`, o Spring vai buscar se a classe `ClienteService` tá anotado com alguma anotação que herda de `@Component` (por exemplo, `@Service` ou `@Repository` ) e cria o objeto por você e passa aqui.

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/controler/ClienteController.java
> +    }
Gostei desse endpoint seu, a idéia é bem legal, de poder pegar o cliente mais velho. 

Isso aqui se qualifica como a nossa primeira lógica de negócio da Confeitaria. Por isso, temos que mover a lógica de negócio que descobre qual é o cliente mais velho para um lugar mais correto. Lembra, lógicas de negócio tem que ficar numa classe marcada como `@Service`. Por isso, por favor, muda essa implementação para um novo método lá na classe `ClienteService` e chama esse novo método aqui. :)

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/controler/ClienteController.java
>      }
Para exercitar um pouco suas habilidades de refatoração, vamos mudar a implementação do método `clienteService.adicionarCliente` para aceitar um objeto da classe `Cliente` ao invés de receber cada um dos valores de nome, idade, etc..

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/repository/ClienteRepository.java
> +public class ClienteRepository implements IClienteRepository{
Essa implementação da interface `IClienteRepository` é baseada num `HashMap`. Podemos ter outras implementações no futuro da mesma interface mas usando outro mecanismo para guardar os dados, como por exemplo um banco de dados. Por isso, acho legal mudarmos o nome dessa classe para algo como `HashMapClienteRepository` para deixar claro para outras pessoas o que ela é .

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/repository/ClienteRepository.java
> +        Cliente cliente1 = new Cliente(nome,idade,telefone,cpf);
Mudar o nome da variável, `cliente1` dá a impressão que existem outros variáveis de clientes, mas na verdade não tem.

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/repository/ClienteRepository.java
> +        mapa.put(cliente.getIdade(), cliente);
Acho que aqui você queria usar o id do cliente, não a idade. :D

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/repository/FuncionarioRepository.java
> +    ArrayList<Funcionario> listaFuncionario = new ArrayList();
Quando a gente declara uma variável de uma classe que na verdade é uma classe herdada de outra abstrata, é sempre recomendado usar o tipo abstrato ao invés do concreto. Em outras palavras, `ArrayList` é o tipo concreto, que implementa a classe `List`. Então quando declarar a variável, declara ela como sendo do tipo `List` para que isso fique genérico para quem for usar depois.

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/repository/FuncionarioRepository.java
> +    ArrayList<Funcionario> listaFuncionario = new ArrayList();
apesar que nesse caso podemos remover essa variável daqui já que é usado o HashMap não?

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/repository/FuncionarioRepository.java
> +    HashMap <Integer, Funcionario> lista = new HashMap<>();
Nome da variável não condiz com o tipo dela.

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/repository/FuncionarioRepository.java
> +        Funcionario funcionario1 = new Funcionario(nome, idade, telefone, cpf, salario);
Mesma coisa sobre o nome da variável, parece que existem outras variáveis de funcionários, mas existe somente uma

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/repository/FuncionarioRepository.java
> +public class FuncionarioRepository implements IFuncionarioRepository{
Mesma observação sobre o nome, mudar para `HashMapFuncionarioRepository`

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/repository/ProdutoRepository.java
> +public class ProdutoRepository implements IProdutoRepository{
Mudar nome do repositório, seguir a convenção já indicada anteriormente.

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/repository/ProdutoRepository.java
> +    HashMap <Integer, Produto> lista = new HashMap<>();
Nome da variável não condiz com o seu tipo

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/repository/ProdutoRepository.java
> +    public void update(Produto produto) {
no método de `add` você usou `produto.getId()` como a chave, mas aqui tá usando `produto.getIdProduto()`. qual é o correto?

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/repository/ProdutoRepository.java
> +        lista.remove(produto);
Você precisa remover o produto pela sua chave no hashmap, não usando o objeto como todo.

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/service/ClienteService.java
> +    @Autowired
Ao invés de usar o `@Autowired` por favor passe a usar uma construtora que receba como parâmetro as dependências necessárias para a classe. O Spring vai automagicamente entender e injetar tudo sem precisar de anotações.

2024-08-11 18:26 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/service/ClienteService.java
> +    ClienteRepository clienteRepository;
Aqui você tá dependendo diretamente da classe concreta do repositório. A ideia é depender da interface `IClienteaRepository` porque dai você pode trocar a implementação concreta (de HashMap para um banco de dados por exemplo) sem precisar mexer na classe de service. Quando você usa a interface, o Spring vai automagicamente pegar a classe concreta que esteja anotada seja com @Service ou @Repository

2024-08-13 00:30 UTC, HelenaPetruz commented on src/main/java/com/mentoria/helena/confeitaria/controler/ClienteController.java
>      }
Para arrumar esse método teria que alterar o método add do Repository, certo? Ficaria desse jeito:  

> public Cliente add(Cliente cliente) {
> Cliente c = new Cliente(cliente.getNome(),cliente.getIdade(),cliente.getTelefone(),cliente.getCpf());
> mapa.put(c.getIdCliente( ), c);
> return c;
>  }
Seria desse modo, mesmo?

2024-08-15 17:50 UTC, alcantaraleo commented on src/main/java/com/mentoria/helena/confeitaria/controler/ClienteController.java
>      }
Isso, mas acho que a implementação seria um pouco diferente. Você já tem um objeto cliente, não precisa criar um novo para passar as informações. Entendo que você poderia simplesmente salvar ele. Testa e veja se funciona :D

2024-08-22 23:50 UTC, HelenaPetruz commented on src/main/java/com/mentoria/helena/confeitaria/controler/ClienteController.java
>      }
Seria apenas adicionar o objeto, recebido no parâmetro, no Hash map, então? 
Desse modo:

> public Cliente add(Cliente cliente) {
        mapa.put(cliente.getIdCliente(), cliente);
        return cliente;
    }

2024-08-23 20:12 UTC, alcantaraleo approved these changes

2024-08-23 20:12 UTC, merged